### ISSUE TITLE
Stripe Governance Ruleset

### ISSUE THREAD

**Issue by kinlane** [postman-open-technologies/linting-rules#32]
This is a production to establish a set of API governance rules for the Stripe API, helping draw more attention to rules, linting, and how the top API providers approach their work.

Project details:

- Create a Public Workspace
- Import [OpenAPI](https://github.com/stripe/openapi)
- [Run all OpenAPI rules against OpenAPI](https://www.postman.com/postman/workspace/postman-open-technologies-governance-rules)
- Aggregate run results into a single JSON file stored as an example within a standalone collection.
- Publish narrative of the work as the overview for the workspace.

Share the results, but also the narrative of what was found. Are there other rules we could add to evolve the ruleset? Any other thoughts, concerns, and problems.

**Comment by MatthewReinbold** [comment]
Analysis of which linting rules fail across the massive (103k+ lines of JS) Stripe API is documented in the second tab of this spreadsheet:
https://docs.google.com/spreadsheets/d/1U-WEoAR8DvupafglbxyhqTi7aZdXzo73RcoPCpuvhac/edit?usp=sharing

An 'N' indicates a linting rule failure. 

Going through this, it seems as though it is not enough to say that rules that pass in every API case comprise a 'Stripe style'; a lack of failure is just as likely caused by the API not expressing the behavior tested for, than it was a correct implementation according to the rule.  

What is fascinating, given the analysis is how Stripe manages the massive single files in their Github repo - https://github.com/stripe/openapi/tree/master/openapi - rather than break them into discrete areas, they combine them into one monolithic description. I'd like to reach out to richardm, the person listed on the repo, and ask about the decision making that led why they manage things that way - what are the tooling ramifications of handling a 3.827MB description; how to they aggregate disparate pieces together? What is their publishing pipeline for this? I know other companies, like Fidelity, had questions for how to manage these things - this line of inquiry could illuminate some solutions for others.

**Comment by MatthewReinbold** [comment]
Twitter DM I left for Richard Marmorstein, the Github contributor:
 
 > "Hello Richard! My name is Matthew and I work with APIs at Postman. Today, I spent a fair amount of time analyzing your work with the Stripe OpenAPI description - 103k+ lines is no easy feat; running it through my scripts instantly had the fans running and memory utilization through the roof. I'd love to learn more about the process that goes into managing that single, canonical file - what kind of management processes, tooling, and compiling considerations go into managing an industry resource that large. I know a lot of companies struggle when their OpenAPI descriptions grow larger than a few thousand lines; the usual approach is to break up the file into domains. People could really benefit from your insight. Is the Stripe approach to managing the API description something you could talk about?"

**Comment by kinlane** [comment]
Like Twilio, agree with your findings and will keep the research for future storytelling. And again, was looking at the journey here over the outcome, and I think you nailed that with the scope of the OpenAPI file. Great storytelling opportunity there. I'd love to see a blog post on the topic. This size of OpenAPI comes up over and over in customer conversations, and we need more storytelling on the subject and opinionated guidance. I'd say that this discussion reflects the mono vs micro repo, and web service vs microservice discussions. I don't think many folks understand the tradeoffs. Let's close this research for now, but the size issue is something that should be continued to be explored.
