### ISSUE TITLE
Twilio Governance Ruleset

### ISSUE THREAD

**Issue by kinlane** [postman-open-technologies/linting-rules#33]
This is a production to establish a set of API governance rules for the Twilio API, helping draw more attention to rules, linting, and how the top API providers approach their work.

Project details:

- Create a Public Workspace
- Import [OpenAPIs](https://www.postman.com/twilio/workspace/twilio-api/overview)
- [Run all OpenAPI rules against OpenAPI](https://www.postman.com/postman/workspace/postman-open-technologies-governance-rules)
- Aggregate run results into a single JSON file stored as an example within a collection.
- Publish the narrative of the work as the overview for the workspace.

Share the results, but also the narrative of what was found. Are there other rules we could add to evolve the ruleset? Any other thoughts, concerns, and problems.

**Comment by MatthewReinbold** [comment]
Analysis of which linting rules fail across the suite of Twilio APIs is documented in the first tab of this spreadsheet:
https://docs.google.com/spreadsheets/d/1U-WEoAR8DvupafglbxyhqTi7aZdXzo73RcoPCpuvhac/edit?usp=sharing

An 'N' indicates a linting rule failure. 

Going through this, it seems as though it is not enough to say that rules that pass in every API case therefore comprise a 'Twilio style'. In many cases, like the rule 'openapi-v3-response-patch-204-status-code', the lack of failure is more likely due to the fact that none of the APIs used the PATCH method, rather than implementing it in such a way to successfully pass a test. 

What can be done, in the meantime, is identifying and promoting useful practices that appear to be often missed ('define-array-boundaries', 'operations-description', etc.) and well as praising consistent good behavior (presence of contact info).

**Comment by kinlane** [comment]
Nice work. That is what I assumed. Didn't expect we'd come up with a guide from it, but figured there would be lots to learn along the way. Agreed, that identifying and promoting useful practice is a great place to start. I also think we can begin to come up with some sort of scoping for rules that determine if there is another rule that should be run first, which as you said would check for PATCH, and then not even run a rule -- rendering it irrelevant, or false / no. I am going to close out for now, but index the sheets for consideration as part of future storytelling.  Thanks for tackling!!
